experiment_name: ${weak_label_type}-${loss_func.loss_type}-${dataset}-${model}

dataset: mnist
model: linear
weak_label_type: complementary_labels
loss_func:
  loss_type: logit_squeezing
  base_loss: cross_entropy
  kwargs:
    exponent: 2.0
    coefficient: 0.03
learning_rate: 0.0003
