experiment_name: ${weak_label_type}-${loss_func.loss_type}-${dataset}-${model}

dataset: mnist
model: mlp500
weak_label_type: complementary_labels
loss_func:
  loss_type: backward
  base_loss: cross_entropy
learning_rate: 0.01
